### ISSUE TITLE
Physics Based Rendering (PBR Shader)

### ISSUE THREAD

**Issue by ducphamhong** [skylicht-lab/skylicht-engine#85]
ref #5

**Comment by Sahi2l** [comment]
Hello sir 

*Very hard I got your gmail and you are not replying us on other social media platforms. If you really see our gmail then please Reply* 


This game is not even on play store(GANG WAR MAFIA) .  Nor are any of its servers running.  this game is completely closed

Can you tell me when the new format of this game will be released on play store

This is my only favorite FPS game and the only favorite of many people with me


*I am attaching some sacreenshot together so that you will understand.  what i want to say*


Tranclet in Vietnamese


Xin chào ông


 * Rất khó, tôi đã nhận được gmail của bạn và bạn không trả lời chúng tôi trên các nền tảng mạng xã hội khác.  Nếu bạn thực sự thấy gmail của chúng tôi thì hãy Trả lời *



 Trò chơi này thậm chí không có trên cửa hàng chơi (GANG WAR MAFIA).  Cũng không có bất kỳ máy chủ nào của nó đang chạy.  trò chơi này đã hoàn toàn đóng cửa


 Bạn có thể cho tôi biết khi nào định dạng mới của trò chơi này sẽ được phát hành trên Play Store không


 Đây là trò chơi FPS yêu thích duy nhất của và là trò chơi yêu thích duy nhất của nhiều người cùng tôi
